# Generated by Django 2.1.5 on 2019-02-28 16:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('upin', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_fn', models.CharField(max_length=30)),
                ('doctor_ln', models.CharField(max_length=30)),
                ('expertise', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('patient_fn', models.CharField(max_length=30)),
                ('patient_ln', models.CharField(max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='scheduling.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='scheduling.Patient'),
        ),
    ]
