# Generated by Django 2.1.5 on 2019-03-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='appointments_per_day',
            field=models.IntegerField(null=True),
        ),
    ]
