# Generated by Django 2.1.5 on 2019-03-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_auto_20190315_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='appointments_per_day',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
