# Generated by Django 2.1.5 on 2019-03-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_remove_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('assistant', 'Assistant')], default='patient', max_length=9),
        ),
    ]
