# Generated by Django 2.2 on 2019-04-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_auto_20190422_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(blank=True, upload_to='doctors'),
        ),
    ]
