# Generated by Django 2.2 on 2019-04-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='appointments_per_hour',
        ),
    ]
