# Generated by Django 2.2 on 2019-04-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_auto_20190422_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(upload_to='doctors'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.ImageField(upload_to='patients'),
        ),
    ]
